// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Accept whatever the host injected: Vercel Postgres (DATABASE_URL/POSTGRES_URL),
    // Prisma Postgres (PRISMA_DATABASE_URL), or pooled (POSTGRES_PRISMA_URL).
    url:
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_URL"] ||
      process.env["PRISMA_DATABASE_URL"] ||
      process.env["POSTGRES_PRISMA_URL"],
  },
});
